spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-w4kmffqu86f3iz7k.us.auth0.com/}
          audiences: ${AUTH0_AUDIENCE:https://dev-w4kmffqu86f3iz7k.us.auth0.com/api/v2/}
      
      client:
        registration:
          auth0:
            client-id: ${AUTH0_AUDIENCE}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid,profile,email
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}

server:
  port: 8080

# Configuración CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true